

#Class for Rosetta Employee Association
class RosettaEmployeeAssociation:
    def __init__(self):
        self.iam_id = ""
        self.employee_record = ""
        self.employee_id = ""
        self.position_number = ""
        self.position_title  = ""
        self.job_indicator = ""
        self.relationship_to_organization = ""         
        self.employee_classification = ""
        self.employee_classification_description = ""
        self.status = ""
        self.hire_date = ""
        self.start_date = ""
        self.fte_percentage = ""
        self.job_type_id = ""
        self.job_type_description = ""
        self.organization_id = ""
        self.organization_title = ""
        self.division_id = ""
        self.division_title = ""
        self.subdivision_id = ""
        self.subdivision_title = ""
        self.subdivision_l4_id = ""
        self.subdivision_l4_title = ""
        self.business_unit_id = ""
        self.business_unit_title = ""
        self.department_id = ""
        self.department_title = ""
        self.department_short_title = ""
        self.reports_to_position = ""
        self.reports_to_iam_id = ""
        self.reports_to_employee_id = ""
        self.is_health_position = ""
        self.is_campus_position = ""
        self.modified_date = ""
        self.create_date = ""

